// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ScreenSound.Data;

#nullable disable

namespace ScreenSound.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231201060246_PopularTabela")]
    partial class PopularTabela : Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ScreenSound.Modelos.Artista", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Bio")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.Property<string>("FotoPerfil")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.HasKey("Id");

                b.ToTable("Artistas");
            });

            modelBuilder.Entity("ScreenSound.Modelos.Musica", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.HasKey("Id");

                b.ToTable("Musicas");
            });
#pragma warning restore 612, 618
        }
    }
}
