// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ScreenSound.Data;

#nullable disable

namespace ScreenSound.Migrations
{
    [DbContext(typeof(Context))]
    partial class ScreenSoundContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ScreenSound.Modelos.Artista", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Bio")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.Property<string>("FotoPerfil")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.HasKey("Id");

                b.ToTable("Artistas");
            });

            modelBuilder.Entity("ScreenSound.Modelos.Musica", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int?>("AnoLancamento")
                    .HasColumnType("int");

                b.Property<int?>("ArtistaId")
                    .HasColumnType("int");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.HasKey("Id");

                b.HasIndex("ArtistaId");

                b.ToTable("Musicas");
            });

            modelBuilder.Entity("ScreenSound.Modelos.Musica", b =>
            {
                b.HasOne("ScreenSound.Modelos.Artista", "Artista")
                    .WithMany("Musicas")
                    .HasForeignKey("ArtistaId");

                b.Navigation("Artista");
            });

            modelBuilder.Entity("ScreenSound.Modelos.Artista", b =>
            {
                b.Navigation("Musicas");
            });
#pragma warning restore 612, 618
        }
    }
}
