services:
  screensoundapi:
    image: ${DOCKER_REGISTRY-}screensoundapi:latest
    container_name: projetoscreensound-screensoundapi
    build:
      context: .
      dockerfile: ScreenSound.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ScreenSoundDB: ${CONNECTION_STRING}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: projetoscreensound-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
