name: Pipeline
on:
  push:
    branches: ["master"]
jobs:
    build:
      name: Pipeline ScreenSound Master
      runs-on: ubuntu-latest
      steps:
         - name: Setup .NET
           uses: actions/setup-dotnet@v2
           with:
             dotnet-version: 8.0.x
         - name: Checkou do código
           uses: actions/checkout@v2
         - name: Execução Unit tests
           run: dotnet test ./ScreenSound.Tests
         # - name: Execução Integration tests
         #   run: dotnet test ./ScreenSound.Tests.Integration
         - name: Publish API
           run: dotnet publish ./ScreenSound.API